sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: X2ECicOONdGjqVJI9zKFKDVmi9ULAkHPDz8SGB/+yIDDylQdIybKKxYQ4ZHz9QPoBPj/BMupI0IXoyDKXXEEl5RmS0si3rteCspLi9yGWGNulbw16Z7P+Q5MjB/0PJqw2TCz37D9radbCDUQIFyRuca88ZhKiq0rWvXrYnSURKHcOjPdOBLEgBdQKCfU+Cp+AC7bMzZPEFGuSLii7/de8bZWQe3C1jUyI+GTWbzrxu7v5ZCg9O0NnjC/1ODrrJNxTSXGFJv/4zVMPBhypm4nV2KoyXHHYteW2Vlgu5NgB4qE85oiNUAP95V/yTbF8JxHQT/fhfX4rLv8Hbg8dWBs74E6s3/GcHCYT9Qr74FhP9XdAYcZd7xZCyLEQu7/ru76/+wHkb+9tsb4+1XA3IvWXwqOPKl4Vs8/LS4uG3cKagIrtNxv3OM5ecCWZaIS5j2XvOOewTJnmS/Xdq8UDC+sGtm/Yu2mskhReFazM99mXZi0pySArbz8lWjx9LDRDQkguZ/xtEehwm30c+79joWan8R22dhT7+XNTqgUlA0Z4zmpkr4hoBHsE4EseClR7DVGG1/TVJHp/IgflpQalLEVwPxDyUSUEwTMHHvWXp5bJJJPJ9a5P0E4O4h9TRVmdb7ASM6YJDPYMuaTAO6XULRV+F0idAz0ikncAXxvekY+GlY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Town-Traveller_4308
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy